### ISSUE TITLE
Sequences created in-runtime via sequence_create doesn't appear on screen

### ISSUE THREAD

**Issue by KeeVeeGames** [YoYoGames/GameMaker-HTML5#299]
Custom made sequences are not visible on screen after adding them in a room with `layer_create_sequence`. This happens because they don't have their `m_channels` fully populated due to the incorrect `gmlcahmmels` setter. It only adds one channel for each keyframe so for example in the position there's only x and no y and in the scale there's only xscale and no yscale, so that's why it's not visible I believe.

This is only applicable after resolving issue #297 because currently it's not possible to even create a sequence on a layer from sequence object struct.

I added a fix for that also to my previous pull request.

**Comment by stuckie** [comment]
Can we get a project to verify this against?

**Comment by stuckie** [comment]
Thanks for reporting this issue, but in order to investigate we will need a small project which shows this issue. Please report this issue again, but ensure you have a suitable project open at the time and you have checked the “Include Project” option on the bug form.

**Comment by KeeVeeGames** [comment]
You guys sure are fast, haha.
You tried to check the issues yourself and couldn't reproduce them, and that's why you're asking for a project, did I get it right? Because otherwise the steps of repro and exact technical causes I specified for both issues, and even the pull request with the ready-made code fixing them opened by me should be pretty self-explanatory.
The pull request was not reviewed on time for some reason, but given that it has been almost a year since then it is possible that both issues were either fixed or transformed in other forms, so that's why you may not be able to reproduce them yourself.
I am not interested anymore in developing for and contributing to HTML5 runtime for the same reasons: too late responses, no reviews on pull-requests (even refusal ones), no in-home fixes instead, just silent limbo. So I couldn't help you there.
Hope, those issues are already non-existent, otherwise you have everything you need: a full description of problems, an explanation of why it is happening and code with fixes to them. Have a nice weekend and thanks for finally answering that, lol!

**Comment by stuckie** [comment]
Apologies for the delay in all of this; a number of tickets managed to get lost but recent GitHub updates have allowed us to modify our workflow and see them again, so we're catching up on lost tickets now.

The project request was to confirm what you were seeing and that your PRs fixed the issues in the way you were expecting.
We've found that it removes all doubt and human error if a bug report has a project attached, set up in the way that the user can reproduce the bug in themselves, so that we can see exactly what has gone wrong and fix it from there; especially as there can be all manner of interactions between things that can cause differences..
There are thousands of bugs on the main bug repository, so taking the time to create a new project, object, etc.. and copy/paste the code x-amount of times can take up a fair chunk of the day, so to have it premade completely reduces that burden, ensures we see what you see, and gives us a ready-made test project to ensure that any fix is the correct one.

Again, I can only apologise for the length of time things have sat waiting.

**Comment by KeeVeeGames** [comment]
Okay, thank you.
That's understandable, my apologies. I will make sure to always provide a project file for future bug reports.
