### ISSUE TITLE
collision_rectangle is failing to register collisions.

### ISSUE THREAD

**Issue by Amon-Arelious-Soza** [YoYoGames/GameMaker-HTML5#41]
I have this code:

`	if ( collision_rectangle(x -16, y + 4, x + 16, y + 4, oPlatParent, false, true) )	
	{
               blah when collision occurs
        }`

Basically, I have a player sprite which is 64x64 pixels. I have a platform which is 64x64 pixels. The platform is parented to oPlatParent. When the player is falling it should collide with the platform and register a collision, which it does on desktop platforms) but HTML5 seems to ignore the collision completely.

It was confirmed as a bug by YoYo bug support. I was wondering if anyone can check the collision_blah() functions and see if anything is wrong?

**Comment by Amon-Arelious-Soza** [comment]
[YYZ of the issue](https://panayiotisyianni.com/mygames/joeretro.yyz)

When you run it in desktop export everything works fine. In html5 the collisions don't work and the alignment of the left text is all off.

left/right arrown keys to move and ctrl to jump. press down arrow to fall down through a plat.

**Comment by Toad06** [comment]
I can see in your sample that Collision Compatibility Mode is enabled.
However it seems like this setting isn't applied correctly because of an obfuscation issue here:

https://github.com/YoYoGames/GameMaker-HTML5/blob/4bf39874b44f9fe8c07bea2899741e81ed5799ab/scripts/_GameMaker.js#L606

This line of code produces something like this (when you run the game in debug mode from the IDE):
`obfuscated_1 = obfuscated_2.Options.obfuscated_3;  // whoops, obfuscated_3 shouldn't be obfuscated!`

I think this could be fixed by changing the line to:
`g_Collision_Compatibility_Mode = g_pGMFile.Options['CollisionCompatibility'];`

However, other Options are not written like this (as a "string"), so I suppose that there exists a list of things that shouldn't be obfuscated - and "CollisionCompatibility" should be added to this list.


@rwkay Any thoughts on that?

**Comment by Amon-Arelious-Soza** [comment]
Ok, I just tried it again with collision compatibility off and it made no difference to the html5 version. It just plain refuses to register collisions.

**Comment by Toad06** [comment]
That's expected in fact. Because of the obfuscation issue, the collision compatibility setting always behaves as if it was set to off (which is not what you want as this indeed completely changes the behavior - even on Windows).

If you want a proof, you could do that:
- Run the game in **debug mode**.
- View page source and open the .js file (joeretro.js).
- In the JS file, search for `Options._` (there should be only 1 match if the search is case sensitive).
- Copy the name of the variable this option is assigned to (var1 = var2.Options.var3 => copy the name of var1 - the name is obfuscated).
- Close the JS file, go back to the game.
- Open the browser's console and run the following code (replace var1 with the game you grabbed):
`var1 = true; room_goto(0);`
- Collisions should work as the collision compatibility mode is now enabled.

**Comment by Amon-Arelious-Soza** [comment]
I'm unclear how to do all that. I do believe though that if you found the collisions working then it must be that. How can this be fixed permanently though?

**Comment by rwkay** [comment]
I have fixed this now within the compiler I will get it cherry picked over so the next Beta (too late for todays) should have the fix... 

Thanks for pointing this out.

**Comment by yoyo-danielc** [comment]
@Amon-Arelious-Soza just checking if this is solved for you now, since the link to your test yyz is dead now?

Thanks

**Comment by Amon-Arelious-Soza** [comment]
Sorry for the late reply. It is solved.
