### ISSUE TITLE
HTML5: Running the attached game for Firefox gives an exception regarding clipboard

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-HTML5#544]
Running the attached game will give the following exception on Firefox only, chrome/gx do not display this error

'clipboard-read' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName

Project is located in the private attachment of https://github.com/YoYoGames/GameMaker-Bugs/issues/7206

Repro

1. Import project
2. Run for HTML5 on Firefox
3. Open Developer tools
4. Observe issue

**Comment by toby-yoyo** [comment]
The game seems to end on load immediately due to an exception in `activate_clipboard`. The audio context is deinitialised on game end, so it is expected that it would be `null`.

On loading the game I'm seeing:

![{4D89B885-BAF8-4FBE-8D55-4B4AFCE3A304}](https://github.com/user-attachments/assets/32ec1b8f-0025-4ff7-90f0-3f4067716702)

As said in the description, this does not occur on Chromium-based browsers.

**Comment by scott-dunbar** [comment]
Oh yes, you are quite right - i did not see that initially amongst the other exceptions will update description accordingly

**Comment by mgeddesGM** [comment]
verified as of  IDE v2026.100.0.1151  Runtime v2026.100.0.1101
